### ISSUE TITLE
Configuring options in _config.yml

### ISSUE THREAD

**Issue by sjaakvandenberg** [hexojs/hexo-browsersync#6]
Hi, I would like to configure my [BrowserSync](http://www.browsersync.io/docs/options/#option-logLevel) options like is possible in [hexo-browser-sync](https://github.com/yuukichi/hexo-browser-sync) for 2.8.3. There I can just do

```yml
browser_sync:
  logLevel: "info"
  ghostMode:
    scroll: true
```

Is this possible for hexo-browsersync?

Thanks for your help, and work on this software.
